server:
  port: ${APP_PORT}

spring:
  application:
    name: profitsoft-unit-5
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}

  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}

mails:
  delay: "300000"