server:
  port: 8081

spring:
  application:
    name: profitsoft-unit-5
  kafka:
    bootstrap-servers: localhost:9092

  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mails:
  delay: "300000"
